Role.create!(name: 'admin')
Role.create!(name: 'poster')
User.create!(name: 'vuong tran', email: 'vuong.tran@asiantech.vn', password: '123456789', password_confirmation: '123456789', role_id: 1)
User.create!(name: 'an nguyen', email: 'an.nguyen@asiantech.vn', password: '123456789', password_confirmation: '123456789', role_id: 2)
Category.create!(name: "Short news")
Category.create!(name: "World Cup")
Category.create!(name: "Euro")

EventDetail.create(name: "goal")
EventDetail.create(name: "get a yellow card")
EventDetail.create(name: "get a red card")
